import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Paper } from '@mui/material'
import styles from '../styles/Home.module.css'
import Form from '../src/components/Form'

export default function Home() {
  const [formValues, setFormValues] = useState('')
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Paper>
        <Form onSubmit={()=>{ throw new Error('not implemented') }}></Form>
      </Paper>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
