name: Unit tests coverage report

on: ["push", "pull_request"]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js v17
        uses: actions/setup-node@v2
        with:
          node-version: 17.7.1
          cache: 'yarn'

      ## Setup yarn
      - name: Install dependencies
        run: yarn install

      ## Running scripts
      - name: Create project config for testing
        run: |
          cp .env.example .env

      - name: Run test and create report
        run: yarn coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN }}
