name: Lint & unit test & audit checks
on: [push]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js v17
        uses: actions/setup-node@v2
        with:
          node-version: 17.7.1
          cache: 'yarn'

      ## Setup yarn
      - name: Install dependencies
        run: yarn install

      ## Running scripts
      - name: Create project config for testing
        run: |
          cp .env.example .env

      - name: Run linting checks
        run: yarn lint

      - name: Run unit tests
        run: yarn test

      - name: Run audit
        run: yarn audit
