name: Periodic Smoke Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * 2,4,6'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js v17
        uses: actions/setup-node@v2
        with:
          node-version: 17.7.1

      - name: Install dependencies
        run: yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          config-file: cypress/configs/smoke.json
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_BASE_URL: https://boulderando.vercel.app/
          NEXT_PUBLIC_SOCKET_API_URL: https://boulderando-api.herokuapp.com/
          CYPRESS_SMOKE_TEST_IGNORE: ${{ secrets.CYPRESS_SMOKE_TEST_IGNORE }}
          CYPRESS_SMOKE_TEST_USER_NAME: ${{ secrets.CYPRESS_SMOKE_TEST_USER_NAME }}
          CYPRESS_SMOKE_TEST_USER_LAST_NAME: ${{ secrets.CYPRESS_SMOKE_TEST_USER_LAST_NAME }}
          CYPRESS_SMOKE_TEST_USER_EMAIL: ${{ secrets.CYPRESS_SMOKE_TEST_USER_EMAIL }}
          CYPRESS_SMOKE_TEST_USER_TELEGRAM_ID: ${{ secrets.CYPRESS_SMOKE_TEST_USER_TELEGRAM_ID }}
          CYPRESS_SMOKE_TEST_USER_PHONE: ${{ secrets.CYPRESS_SMOKE_TEST_USER_PHONE }}
          CYPRESS_SMOKE_TEST_URBAN_SPORTS_NO: ${{ secrets.CYPRESS_SMOKE_TEST_URBAN_SPORTS_NO }}

